version: '3.9'

services:
  mongo:
    build:
      context: ./mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - user-network
    restart: unless-stopped

networks:
  user-network:

volumes:
  mongodb-data:
