version: '3.9'

# List of services
services:
  user-service: # User service configuration
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    env_file:
      - ./user-service/.env
    depends_on:
      - mongo
    networks:
      - user-network
    restart: unless-stopped
  mongo: # Mongo database configuration
    image: mongo:4.4
    ports:
      - '27017:27017' # Expose port 27017 for communication with the services
    volumes:
      - mongodb-data:/data/db

networks: # Network configuration
  user-network:

volumes: # Volume configuration
  mongodb-data: # Volume for the database

