version: '3.9'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - '${PORT}:${PORT}'
    environment:
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
    env_file:
      - ./user-service/.env
    depends_on:
      - mongo
    networks:
      - user-network
    restart: unless-stopped
  mongo:
    image: mongo:4.4
    ports:
      - '27017:27017'

networks:
  user-network:

volumes:
  mongodb-data:
