export const COMMISSION_DETAILS_REQUEST = 'COMMISSION_DETAILS_REQUEST';
export const COMMISSION_DETAILS_SUCCESS = 'COMMISSION_DETAILS_SUCCESS';
export const COMMISSION_DETAILS_FAIL = 'COMMISSION_DETAILS_FAIL';
export const COMMISSION_DETAILS_RESET = 'COMMISSION_DETAILS_RESET';
