// order create
export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

// order details
export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

// shipment
export const SHIPMENT_CREATE_REQUEST = 'SHIPMENT_CREATE_REQUEST';
export const SHIPMENT_CREATE_SUCCESS = 'SHIPMENT_CREATE_SUCCESS';
export const SHIPMENT_CREATE_FAIL = 'SHIPMENT_CREATE_FAIL';
export const SHIPMENT_CREATE_RESET = 'SHIPMENT_CREATE_RESET';

// order pay
export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

// order sms
export const ORDER_SMS_REQUEST = 'ORDER_SMS_REQUEST';
export const ORDER_SMS_SUCCESS = 'ORDER_SMS_SUCCESS';
export const ORDER_SMS_FAIL = 'ORDER_SMS_FAIL';
export const ORDER_SMS_RESET = 'ORDER_SMS_RESET';

// order email
export const ORDER_EMAIL_REQUEST = 'ORDER_EMAIL_REQUEST';
export const ORDER_EMAIL_SUCCESS = 'ORDER_EMAIL_SUCCESS';
export const ORDER_EMAIL_FAIL = 'ORDER_EMAIL_FAIL';
export const ORDER_EMAIL_RESET = 'ORDER_EMAIL_RESET';

// order list by user
export const ORDER_DETAILS_BY_USER_ID_REQUEST = 'ORDER_DETAILS_BY_USER_ID_REQUEST';
export const ORDER_DETAILS_BY_USER_ID_SUCCESS = 'ORDER_DETAILS_BY_USER_ID_SUCCESS';
export const ORDER_DETAILS_BY_USER_ID_FAIL = 'ORDER_DETAILS_BY_USER_ID_FAIL';
export const ORDER_DETAILS_BY_USER_ID_RESET = 'ORDER_DETAILS_BY_USER_ID_RESET';
