apiVersion: v1
kind: Service
metadata:
  name: email-service
  labels:
    app: email-service
spec:
  selector:
    app: email-service
  ports:
    - protocol: TCP
      port: 9123
      targetPort: 9123
  type: LoadBalancer
