apiVersion: v1
kind: Service
metadata:
  name: admin-service
  labels:
    app: admin-service
spec:
  selector:
    app: admin-service
  ports:
    - protocol: TCP
      port: 9122
      targetPort: 9122
  type: LoadBalancer
