version: '3.9'

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - '${PORT}:${PORT}'
    environment:
      PORT: ${PORT}
      MONGO_URI: ${MONGO_URI}
    depends_on:
      - mongo
    networks:
      - user-network
    restart: unless-stopped
  mongo:
    build:
      context: ./mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
    networks:
      - user-network
    restart: unless-stopped

networks:
  user-network:

volumes:
  mongodb-data:
